### PR TITLE
Udpate geth to 1.5.7

### PR DESCRIPTION
**Pull request by luclu**
### Tested:
---
- [x] macOS
- [x] linux32
- [x] linux64
- [ ] win32
- [ ] win64
---
- [x] stability
- [x] sending

### CODE REVIEW

**Comment by frozeman** [comment]
Please lets include the fixed zip versions for this release still @fjl

**Comment by fjl** [comment]
ok

**Comment by frozeman** [comment]
We need to put a halt on that one, geth will release a new version 1.5.8 shortly succeeding this one.

**Comment by luclu** [comment]
I will create a new PR for 1.5.8.

**Pull request closed without merging**
