### PR TITLE
Update to latest Solidity

### PR DESCRIPTION
**Pull request by evertonfraga**
1.4.12 was released, but not on NPM. Waiting for it to conclude this PR.

### CODE REVIEW

**Comment by evertonfraga** [comment]
Updated to the fresh `0.4.13`.

**Comment by PatchRanger** [comment]
@evertonfraga According to https://www.npmjs.com/package/solc , the most fresh is `0.4.15` - please update to 0.4.15. Also please resolve the conflicts.

**Comment by evertonfraga** [comment]
Thanks, @PatchRanger, we are aware. It'll be updated right before the next release.

**Comment by evertonfraga** [comment]
triggering travis build

**Comment by evertonfraga** [comment]
Superseded by https://github.com/ethereum/mist/pull/2960.

**Pull request closed without merging**
