### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by luclu**

### CODE REVIEW

**Comment by evertonfraga** [comment]
LGTM. will test during the day

**Comment by luclu** [comment]
Could you please also merge https://github.com/ethereum/mist/pull/2282 and update this branch thereafter?

**Comment by luclu** [comment]
@evertonfraga @alexvandesande I need some help in getting this one going :)

**Comment by frozeman** [comment]
"Couldn't update "develop": Required status check "continuous-integration/travis-ci" is expected. At least one approved review is required by reviewers with write access."

**Comment by luclu** [comment]
Thank you Fabian, I restarted the build as some other tests hit their timeouts:

bildschirmfoto 2017-05-22 um 11 23 18

**Comment by frozeman** [comment]
I still can't update the branch?

**Comment by luclu** [comment]
Me neither:
> Couldn't update "develop": You're not authorized to push to this branch.

Perhaps this was due to the missing approval on this protected branch? (..would be some bug with github..)

@frozeman Could you please retry?
If it doesn't work thereafter, I will close and recreate this PR /and get in contact with github.

**Pull request merged**
