### PR TITLE
Swarm integration

### PR DESCRIPTION
**Pull request by MaiaVictor**
This reimplements the old Swarm pull request on top of `develop`, i.e., without the preloader changes.

### CODE REVIEW

**Comment by evertonfraga** [comment]
- [x] Uploading single files to swarm
- [x] Local page on http server displaying swarm-served assets
- [ ] Uploading multiple files to swarm
- [ ] Accessing a swarm website

**Comment by alexvandesande** [comment]
I tried uploading two apps, pure html, after build process. The ENS app (current docs folder on the GitHub) returned this error: 

```
{ RequestError
    at ClientRequest.req.once.err (/Users/alex/dev/mist/node_modules/got/index.js:73:21)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ECONNREFUSED',
  message: 'connect ECONNREFUSED 127.0.0.1:8500',
  host: 'localhost:8500',
  hostname: 'localhost',
  method: 'POST',
  path: '/bzzr:/' }
```

And the team management app in react (much smaller app) returned this error: 

```
{ Error: ENFILE: file table overflow, open '/Users/alex/dev/mist-team/.git/objects/99/f92bf09505511ce1f1167aa7ea16bbf42d8e37'
  errno: -23,
  code: 'ENFILE',
  syscall: 'open',
  path: '/Users/alex/dev/mist-team/.git/objects/99/f92bf09505511ce1f1167aa7ea16bbf42d8e37' }
```

**Comment by alexvandesande** [comment]
Another test case that failed to me: photoalbum.eth is owned and points to a swarm hash:

screen shot 2017-06-28 at 12 33 39

But ctrying to access the link in question will open a blank page (but won't fail completely as it's loading a favicon): bzz://d74075a99945d545839fecc463207c6ed9798dcf16cf9e4073936b8579990728/ 

screen shot 2017-06-28 at 12 33 35

Trying to access directly using the ens also results in an error: bzz://photoalbum.eth/ `can't resolve: no contract code at given address`

screen shot 2017-06-28 at 12 35 58

The same urls will work on swarm gateways currently:

http://swarm-gateways.net/bzz://photoalbum.eth/

http://swarm-gateways.net/bzz://d74075a99945d545839fecc463207c6ed9798dcf16cf9e4073936b8579990728/

It's not clear if it's a Mist issue or a swarm issue, but I'd say we cannot consider this feature ready and mergeable while these basic examples won't load

**Comment by MaiaVictor** [comment]
@alexvandesande this seems to be some Swarm-related problem. Tried opening http://localhost:8500/bzz://photoalbum.eth/ in a normal browser and it doesn't work too, while http://swarm-gateways.net/bzz://photoalbum.eth/ does. Could the Swarm devs shed some light on this?

**Comment by lmars** [comment]
@MaiaVictor are you connecting your local swarm node to a testnet Ethereum node? We have a pull request to support using mainnet (https://github.com/ethereum/go-ethereum/pull/14646), but for now you will need to connect swarm to testnet and use testnet ENS.

**Comment by homotopycolimit** [comment]
swarm-gateways uses Ropsten ENS currently.

I am the owner of photoalbum.eth
I registered a hash on mainnet as a test, but until swarm uses mainnet ENS, I can't use it. Waiting for this PR: https://github.com/ethereum/go-ethereum/pull/14646

**Comment by alexvandesande** [comment]
LGTM!

**Pull request merged**
