### PR TITLE
Remove old, redundant code

### PR DESCRIPTION
**Pull request by hiddentao**
Remove old, redundant code.

### CODE REVIEW

**Comment by alexvandesande** [comment]
Aren't we using popupWindow.js for launching the new accounts page?

**Comment by hiddentao** [comment]
I refactored that all into `modules/windows.js`.

**Comment by alexvandesande** [comment]
Yes, tested and it works. Will wait for a bit for another 👍 and eventually merge it

**Comment by luclu** [comment]
Sorry guys this PR/branch disabled the import-dialog for me. Also I don't get any onboarding screen on a vanilla osx (I moved `~/Library/Application Support/Mist` and `~/Library/Ethereum`).

I don't know that much about branching strategies, but the current process either is a mess or it is just confusing me (which is about as bad 😞).

**Comment by hiddentao** [comment]
@luclu I wonder if some cacheing is involved in the issues you're having, thought I can't think where the cache might be.

**Comment by alexvandesande** [comment]
I didn't have any of these problems Luca

**Pull request merged**
