### PR TITLE
Change README.md to use 'Navigator' instead of 'Browser'

### PR DESCRIPTION
**Pull request by doppio**
Update the README to use the term 'Navigator' rather than 'Browser' to avoid confusion with web browsers like Chrome or Firefox. See Alex's comment on #821.

### CODE REVIEW

**Comment by alexvandesande** [comment]
I like the idea but I'm not sure there's much public support:

https://twitter.com/avsa/status/756870679086174208

**Comment by doppio** [comment]
Ah, okay. What do you think about just removing the word "Browser" altogether as a couple people suggest on the poll? May be worth running another poll on that?

**Comment by hiddentao** [comment]
I'd probably leave it as Browser too as it's easy for people hearing to understand what it does.

**Comment by luclu** [comment]
I personally have to consent with @hiddentao. I regard Ethereum to be already conceptionally complicated enough as to elide these kind of skeuomorphism.

**Comment by alexvandesande** [comment]
I'm closing this for now. Although I still have a nice feeling towards Navigator!..

**Pull request closed without merging**
