### PR TITLE
Korean Translation

### PR DESCRIPTION
**Pull request by atomrigs**
Added Korean Translation

### CODE REVIEW

**Comment by alexvandesande** [comment]
Thanks! If you also want the wallet interface to be translated, you'll need to do it here:

https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/i18n/app.en.i18n.json
https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/i18n/wallet.en.i18n.json

Also add your language to these lists:

https://github.com/ethereum/mist/blob/develop/interface/project-tap.i18n
https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/project-tap.i18n

**Comment by atomrigs** [comment]
I added all files and update the tab lists as you requested.

**Comment by alexvandesande** [comment]
Please merge this PR so I can then merge this with squash: https://github.com/atomrigs/mist/pull/1

**Comment by atomrigs** [comment]
The PR was merged.

**Comment by alexvandesande** [comment]
Thanks @atomrigs

**Comment by woniesong92** [comment]
@alexvandesande Is there any more translation needed for Korean?

**Comment by MELCHEZEDEK776** [comment]
Yes!! Very Cool, where are you from? I'm still in the midst of learning
python and github. But yes, all languages spoken fluently is a huge benefit
to the community.

**Pull request merged**
