### PR TITLE
Untrack public/i18n/

### PR DESCRIPTION
**Pull request by luclu**
follow-up on #679

The automatically pulblic/i18n folder is - I think - unecessarely tracked in git.

### CODE REVIEW

**Comment by hiddentao** [comment]
Agreed!

**Comment by luclu** [comment]
I will look into meteor/gulp-automatisation to populate `public/i18n` a prior the packaging: https://github.com/ethereum/mist/issues/691

**Comment by alexvandesande** [comment]
When you finish this, please apply the same solution to the wallet-dapp

**Comment by luclu** [comment]
This PR without additional i18n processing by meteor will only bundle english strings.
Looking into this in: https://github.com/ethereum/mist/issues/691

**Comment by frozeman** [comment]
Thats why it needs to run meteor first to produce the other i18n files. 
Bundling always worked before :)

we would need to add the step to the gulp file to run meteor before and quit it after a while. 

As this is quite annoying, it might just be better to keep the files in the repo....

**Comment by luclu** [comment]
You are right. The best way I figured out - apart from that - is to replicate tapi18n-bundler's process in gulp...
`meteor build` has different usecases and can't be leveraged for this.

**Pull request closed without merging**
