### PR TITLE
chore(package): update electron to version 2.0.0

### PR DESCRIPTION
**Pull request by fredbuluku**
Closes #3851
Wonderful 
#### What does it do?
It Improves the living situation and standards of people.
#### Any helpful background information?
Any information that lead to the hopeful.
#### Which code should the reviewer start with?
Any for three checks that have passed successfull.
#### New dependencies? What are they used for?
They need to be taken care of.
#### Relevant screenshots?
Crypto currency

### CODE REVIEW

**Comment by fredbuluku** [comment]
> separate the checks

> stop the merg

> g

**Comment by fredbuluku** [comment]
Separate the checks

**Comment by marcgarreau** [comment]
Thanks for your PR. This major version bump will require an investment of testing: see failing Travis jobs. Our team has a couple higher priority items at the moment before we can get to this. Please feel free to troubleshoot the failures if you can.

**Comment by alexvandesande** [comment]
Thanks but this is a duplicate of https://github.com/ethereum/mist/pull/3851. Closing this one as the older one takes priority.

**Pull request closed without merging**
