### PR TITLE
Added --help, --version and --mode cli parameters

### PR DESCRIPTION
**Pull request by hiddentao**
```
Usage:
mist [options]

Options:
  --version   Display app version
  -h, --help  Show help                                                [boolean]
```

Note that on my system I can get this work even in dev mode, i.e. I get `path/to/Electron . [options]`.

### CODE REVIEW

**Comment by hiddentao** [comment]
Need to do a bit more work on this for OS X. In progress.

**Comment by hiddentao** [comment]
Working on Mac now:

```js
/Applications$ Mist.app/Contents/MacOS/Electron --version
0.5.2
```

**Comment by hiddentao** [comment]
Added `--mode` parameter that allows you to set app model to either `mist` or `wallet` without having to edit main.js

**Comment by 5chdn** [comment]
Cool, I want to have something like `--client /path/to/geth`, is that possible? ref #264 :-)

**Comment by hiddentao** [comment]
@5chdn Yep that would be easy to put in. Perhaps we can call it `--geth` instead.

I'm guessing the logic could be:  if `--geth` provided then always use that version of geth. If not found then error (i.e. don't use the bundled fallback).

**Comment by frozeman** [comment]
@hiddentao did you test this with the bundled version on mac OS X as well?
Concerning the geth flag, i would rename this to `gethpath` and `ethpath`.

And i think it should not store this as the default path, as mist ships his own version on purpose, as its the version its optimised for. If people choose to set their own version, than they do this at a risk of incompatibility and can create a symlink, or script etc..

**Comment by hiddentao** [comment]
@frozeman Yep, you can use the command-line options with the bundled version as long as you run it from the terminal, as illustrated in my previous comment above.

As for my comment that Mist should _always use that version of geth_ supplied on the command-line I should have made that clearer. I meant that for that running instance of Mist it should only use that supplied version of geth. I agree with you that Mist should by default always use it's bundled version unless `gethpath` is supplied as an option.

**Comment by 5chdn** [comment]
Isn't mist client-agnostic? So `--ethpath` or `--gethpath` would be limiting to two clients. `--client` could point to any executable which starts an ethereum node with ipc socket.

**Comment by frozeman** [comment]
@5chdn thats already the case, if mist detects a running node on the default pic path, it uses this one... So the path flag wouldn't change a thing here. It would only be useful, if you want mist to start that node for you.

Eth and geth have a slightly different way to start, therefore we would need this separation for now. Otherwise i would agree that `--nodepath` is better...

**Comment by hiddentao** [comment]
So just to be clear, we want to add `--ethpath` and `--gethpath`. i can go ahead and work on that. Having said that, If we could merge this in as it is as a first step that would be great.

**Comment by hiddentao** [comment]
Added `--gethpath` and `--ethpath` parameters

**Comment by hiddentao** [comment]
Replaced by #443

**Pull request closed without merging**
