### PR TITLE
Nav bar glitch and new art for Mist

### PR DESCRIPTION
**Pull request by alexvandesande**

### CODE REVIEW

**Comment by hiddentao** [comment]
What's the nav bar glitch I need to test?

**Comment by alexvandesande** [comment]
Sometimes you would put an URL and it would load that page but not update the url element and therefore you couldn't pin it to the sidebar. Basically I had to go through multiple URLs old and new until the bug reproduced but then it would happen all the time

**Comment by luclu** [comment]
fyi your last commit added some log to the tree.

**Comment by alexvandesande** [comment]
Thanks Luca, I removed it now

**Comment by luclu** [comment]
Fixed it for me.

**Pull request merged**
