### PR TITLE
Choose account popup

### PR DESCRIPTION
**Pull request by evertonfraga**
Here the user will have the ability to choose among her/his accounts from a modal to use on the current Dapp. The idea is to provide more information about what's being shared.

this is a work in progress.

### CODE REVIEW

**Comment by alexvandesande** [comment]
This branch needs merging. What's the update on this progress?

**Comment by hiddentao** [comment]
What's the status of this?

**Comment by evertonfraga** [comment]
@hiddentao still some progress to make. Lacks pin to sidebar checkbox, and some webview interactions.

**Comment by evertonfraga** [comment]
Quick update on this PR: 

The rethought browser bar is now much simpler and won't have that unfolding section.
screenshot 2016-07-01 12 08 48

The new choose account popup will provide more detailed information, though being easy to use.
screenshot 2016-07-01 12 09 59

**Comment by alexvandesande** [comment]
Looking good! But some issues I've noticed testing it:

* When you click on the pop-up on an app already added, it should start with the selected accounts already selected
* It's not loading the favicon, always showing the globe icon, nor the url or the name of the app
* When you select "create new account" it should at minimum return with that one selected on the next screen.
* It's not removing the tab when you click X but this is a bug you're already aware

**Comment by evertonfraga** [comment]
After @hiddentao's sync fix, I've added the pin/unpin Tab ability. Now ready for testing.

**Comment by evertonfraga** [comment]
@luclu Including #554 here. 

screenshot 2016-07-19 23 28 55

**Comment by alexvandesande** [comment]
merged with https://github.com/ethereum/mist/pull/1023

**Comment by miderose** [comment]
Hi, I'm using mist 0.8.7; 
It seems the mist.requestAccount does not execute the callback...

this function:
```javascript
    mist.requestAccount(
        function (e, account) {
            console.log("done");
            console.log(e, account);
        }
    );
```
shows the accounts modal, but never execute the callback after I choose/create an account.

Is this feature released or it's in a developing state yet?

**Pull request closed without merging**
