### PR TITLE
Fully automated UI testing

### PR DESCRIPTION
**Pull request by hiddentao**
**WIP**

* Automated production app UI testing using [spectron](https://github.com/electron/spectron).

### CODE REVIEW

**Comment by hiddentao** [comment]
Made some headway in terms of getting the app started up. But spectron is unable to detect the window properly. Am going to upgrade Electron to the latest version (so that I can use latest spectron with all recent bugfixes too).

**Comment by hiddentao** [comment]
Made some more progress, but now am getting a `Meteor is not defined` error when the window loads up. This only happens when I run the app from spectron (the test framework), not when I run it directly. I haven't yet figured out what the problem is.

**Comment by frozeman** [comment]
It might be a path issue, that can't load the meteor javascript files properly?
Meteor is only undefined if its either not at all loaded, or some errors happened during executions.

**Comment by hiddentao** [comment]
I've narrowed it down. For some reason in test launch mode it doesnt' setup all the globals in `window` that i needs. It also can't find the `moment` module. The JS code is minified and concatenated (I used the `--debug` flag with meteor build to prevent minification but that also prevent concatenation, and meteor-build-client's index file logic construction would no longer work :/). 

I could spend more hours on this but I don't really want to right now. I'm going to see if I can it working without building the final package.

**Comment by hiddentao** [comment]
Did a quick test without building final meteor app - doesn't quite work as expected. Gonna leave this PR for a bit and revisit it later.

**Comment by hiddentao** [comment]
AWW YEAAH!

I figured out [the issue](https://github.com/electron/spectron/issues/69) and came up with a solution (basically don't show the splash screen, just show the main screen when ready). 

So the basic test now works. It checks the account balance showing the wallet.

To run them yourself:

1. Build the production wallet app
2. Run `gulp test-wallet`

**Comment by hiddentao** [comment]
Unable to get this working decently in Travis CI - it takes forever to build the wallet distributable. Presumably because it has to download all the meteor package dependencies and then build the meteor app. Build is already running at 12 minutes and it's still building the Meteor package -> https://travis-ci.org/ethereum/mist/builds/140727836

**Comment by alexvandesande** [comment]
Was testing today, got this error:

```
  basic.test.js
    1) "before all" hook


  0 passing (26ms)
  1 failing

  1) basic.test.js "before all" hook:
     Error: Unable to find "geth" executable in PATH
      at new Geth (node_modules/geth-private/index.js:36:15)
      at module.exports (node_modules/geth-private/index.js:362:10)
      at Context._module.exports.(anonymous function).before (test/_base.js:36:19)
      at next (native)
      at onFulfilled (node_modules/co/index.js:65:19)
      at node_modules/co/index.js:54:5
      at Context.co (node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co/index.js:30:15)
      at Hook.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)



[18:02:21] 'test-wallet' errored after 1.55 s
[18:02:21] Error in plugin 'gulp-spawn-mocha'
Mocha exited with code 1
```

What's the ```geth-private``` node module? What about the Spawn Mocha?

**Comment by hiddentao** [comment]
It can't find the `geth` executable in PATH. I'll change it so that it uses the one we download via gulp.

**Comment by hiddentao** [comment]
`geth-private` is my geth wrapper which makes it easy to do private chains - https://github.com/hiddentao/geth-private

`gulp-spawn-mocha` runs [Mocha](https://mochajs.org/) tests in a separate process.

**Comment by hiddentao** [comment]
Should find geth executable in mist folder now.

**Comment by alexvandesande** [comment]
It works! Awesome, Ram, thanks. Will merge

```
(node:33410) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
You can select a platform like: --platform (all or darwin or win32 or linux)
Mist version: 0.7.6
Electron version: 1.2.5
[10:50:59] Using gulpfile ~/dev/mist/gulpfile.js
[10:50:59] Starting 'test-wallet'...


  basic.test.js
    tests
      ✓ title
      ✓ account balances
      ✓ deposit into account (37186ms)


  3 passing (2m)

[10:53:02] Finished 'test-wallet' after 2.05 mim
```

**Pull request merged**
