### PR TITLE
Complete Albanian translation

### PR DESCRIPTION
**Pull request by alter2000**
Short changes list:

- Corrected grammar and spelling errors,
- Changed string order to match that of the English files (easier to improve later on)
- Translated the rest of the strings
- Changed formatting of the mist.en.i18.json file to fit in with the rest (more of a pet peeve)

Hope I helped!

### CODE REVIEW

**Comment by evertonfraga** [comment]
Thanks for your contribution @alter2000. It is very welcome.

The tests are failing, though. Maybe the JSON file has some sort of syntax error. Can you check that, please?

**Comment by alter2000** [comment]
I'm doing what I can, but I'm in a remote area with barely enough EDGE signal. I'm sorry I can't check this out quickly.

**Comment by evertonfraga** [comment]
I can review it for you and fix what's necessary. no worries!

**Comment by evertonfraga** [comment]
I've spotted the issue. Will merge and fix right after.

**Pull request merged**
