### PR TITLE
check for system-wide installation of nodes; dynamically populate node-menu

### LINKED ISSUE #264: Look for a system wide installation of geth or eth
I'm maintaining the mist packages for ArchLinux and need some guidance.

Starting up mist always tries to start a geth node in `${pkgdir}/usr/share/${pkgname}/resources/node/geth/geth`, but usually people install and maintain their own version of geth or eth in their system, e.g., `/usr/bin/geth`...

Would it be possible that mist checks whether any suitable client is available in `$PATH` before starting it's own node?

Discussion from [AUR](https://aur.archlinux.org/packages/mist/):

> For some odd reason /usr/share/mist/resources/node/geth/geth has no execution privileges after installation with pacman. This is why I'm getting the same error as @notungx when I run mist. Adding the privilege solves the problem.
> 
> The file is not marked as executable probably because it's unpacked from a .zip achive, which has no concept of access privileges. I see that PKGBUILD explicitly sets privileges for libnode.so and Ethereum-Wallet. It should be doing that to geth as well. Please add this line at the end of package():
> 
> ```
> chmod 755 "${pkgdir}/usr/share/${pkgname}/resources/node/geth/geth"
> ```
> 
> For a moment I thought that maybe lack of exacutable flag is deliberate - after all geth is an optional dependency here. But no - mist tries to use its own copy of geth even if you install the geth package from AUR. It does not seem to detect /usr/bin/geth. The dependency is misleading and should be removed.
> 
> The error and the dependency make it look as if geth wasn't bundled with mist until very recently. Is this what happened here? 

And:

> I get the following error after executing mist:
> 
> ```
> CONNECT to IPC PATH: /home/santi/.ethereum/geth.ipc
> CONNECT to IPC PATH: /home/santi/.ethereum/geth.ipc
> NODECONNECTOR ERROR { [Error: connect ECONNREFUSED /home/santi/.ethereum/geth.ipc]
> code: 'ECONNREFUSED',
> errno: 'ECONNREFUSED',
> syscall: 'connect',
> address: '/home/santi/.ethereum/geth.ipc' }
> Node type: geth
> Network: main
> Start node from /usr/share/mist/resources/node/geth/geth
> Stopping nodes...
> Starting geth node...
> UNCAUGHT EXCEPTION { [Error: spawn EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
> Stopping nodes...
> ```
> 
> In my laptop works just executing mist without the need of executing geth first... any ideas?

Should I make the shipped geth binary executable for now? I would prefer using the system wide installation of geth.

### PR DESCRIPTION
**Pull request by luclu**
closes #264

This current state of this PR will make `getNodePaths.js` to:
- `getNodePaths.probe()`
  - enumerate bundled nodes
  - check if system-installation of the relevant nodes are available (only Linux and mac)
  - gather and compare their versions
  - store the relevant (latest version's) paths in a `resolvedPaths[type] => {type:{path:version}}` dictionary
  - takes about 800ms with bundled + system instances of geth + eth (macbook pro, SSD)
- `getNodePaths.query(nodeType)`
  - returns preferred path of node

Prefers the latest version of a chosen node. Also system installation of node has higher priority. 
#### TODO
- [x] abstract to make drag and drop addition of any node possible (like parity)
- [x] make develop and production compatible
- [x] use promises
  - [x] to collect external command's outputs
    - [ ] refactor promise structure (race conditions)
  - [x] to integrate with `ethereumNode.js`
- [x] debug log entries
- [x] start `probe()` as soon as initial node connection times out (don't wait the 3 seconds)
  - [x] promisify to prevent timeout
- [x] basic error handling
- [x] populate node menu labels dynamically
  - [x] add version string
  - [x] hide if only one node type is available 
  - [ ] initiate rebuild of appMenu (gives an error); don't wait for node startup to trigger repopulate
- [ ] rebase on #972 and #1228 once merged

### CODE REVIEW

**Comment by alexvandesande** [comment]
How's the progress here Luca? You seem to be doing some interesting stuff

**Comment by 5chdn** [comment]
Tested on ArchLinux. :+1:

**Comment by evertonfraga** [comment]
@luclu any status on this PR? i can test along with #1228 if needed.

**Comment by luclu** [comment]
@hiddentao what functionality this PR provides is not available via the new node-manager and thus should be added to it if desirable?

**Comment by hiddentao** [comment]
@luclu The drag-and-drop support for Parity - how exactly will that work?

The new client-binaries library would be able to scan for download Parity binaries. But at present we have no UI for letting the user choose what client they wish to use. I was wondering if adding this is a good idea - e.g. we can provide a command-line flag which tells Mist to first show a window showing available clients for the system (availability calculated using client-binaries). The user would then be able to choose which client they want to use for that run. Of course, one issue with doing this is that since Geth and Parity use different chaindata and keystore folders the user will not be able to seamlessly pick up where they left off with the previous client in terms of chain sync.

What do you think?

**Comment by luclu** [comment]
@hiddentao I think all functionality of this PR was superseded  by the current implementation of the clientBinaryManager.

I will close this.

**Pull request closed without merging**
