### PR TITLE
Added NPM shrinkwrap

### PR DESCRIPTION
**Pull request by hiddentao**
This ensures all dependency and sub-dependency versions are fixed.

### CODE REVIEW

**Comment by frozeman** [comment]
How would that work? What does `npm update` do now? is simply `npm install` enough?

**Comment by luclu** [comment]
From my understanding this pretty much omits the `npm update` functionality leaving us with `npm install`.

**Comment by frozeman** [comment]
Yeah, but how would we update?

**Comment by luclu** [comment]
`npm install --save` I guess. @hiddentao?

**Comment by hiddentao** [comment]
Yeah npm install is enough now. But it won't update to the lates versions 
of the packages.
---
Director
HiddenTao Ltd

www.hiddentao.com

**Pull request merged**
