### PR TITLE
Updated README.md to reflect the addition of submodules support.

### PR DESCRIPTION
**Pull request by bobsummerwill**
Updated README.md to reflect the addition of submodules support.  Added sudo to the electron install instructions, because this is a global node installation.

### CODE REVIEW

**Comment by frozeman** [comment]
Please remove the sudo, as it is no necessary when you setup you system correctly ;)

Additional you should add then `$ git submodule update --init` step.

Thanks a  lot for your addition

**Comment by bobsummerwill** [comment]
Please could you clarify "correctly"?   On my Mac, without the sudo it is no dice for that kind of global npm install.

I will add the submodules command for sure.

**Comment by bobsummerwill** [comment]
OK, @frozeman.   Good to go!   Please do let me know what "correct" means for OSX.   Thank you.

**Comment by frozeman** [comment]
You need to set the permission of `/usr/local/lib/node_modules` to your user. Then you never need sudo again.

**Comment by frozeman** [comment]
Thanks :+1:

**Comment by bobsummerwill** [comment]
np.   What is the magic mantra?   I will get that working and then add that to the README too.

I am trying ... but not quite right:

sudo chown -R bob /usr/local/lib/node_modules

**Comment by frozeman** [comment]
should work. I used path finder for that.

**Pull request merged**
