### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by korvus**

### CODE REVIEW

**Comment by alexvandesande** [comment]
Thanks for the work @korvus 

In order to make the translation complete, could you also do the same for the wallet strings, please? https://github.com/ethereum/meteor-dapp-wallet/tree/master/app/i18n

**Comment by frozeman** [comment]
Can you also please translate the `app.en.json` file?

**Comment by V1C0D3R** [comment]
Sorry, I did not see that

**Comment by frozeman** [comment]
I merged now https://github.com/ethereum/mist/pull/460

**Pull request closed without merging**
