### PR TITLE
Added connect event to the IPC backend

### PR DESCRIPTION
**Pull request by frozeman**
This PR, adds the `connect` event to be send down from the IPC backend and also fixes small things in the IPC wrapper.

Ideally we commit fixes for #917 into this branch @hiddentao

### CODE REVIEW

**Comment by hiddentao** [comment]
How can I test this out?

**Comment by frozeman** [comment]
Simply add the `web3.currentProvider.on('connect', function)` function and then quit the running node, and restart it after.

**Comment by hiddentao** [comment]
How are you quitting the running node and restarting it? Through Mist? So are you changing network or something?

**Comment by frozeman** [comment]
Canceling manually. If you don't have any idea how to fix the uncaught connection error for now, i would suggest we merge that now and fix the other later

**Comment by hiddentao** [comment]
Yep, agree with doing the merge now.

**Pull request merged**
