### PR TITLE
cleanup i18n files

### PR DESCRIPTION
**Pull request by luclu**
As proposed in https://github.com/ethereum/mist/issues/888.

### CODE REVIEW

**Comment by frozeman** [comment]
I don't understand that PR, why are you removing kr?

**Comment by luclu** [comment]
`kr` isn't ISO-639-1. https://github.com/TAPevents/tap-i18n/blob/master/lib/plugin/etc/language_names.js#L64
We already switched to the correct `ko`.

**Comment by frozeman** [comment]
why you added these other languages then?

can you please rebase?

**Comment by luclu** [comment]
Have a look at this table: https://github.com/ethereum/mist/issues/888#issuecomment-228544829
`al` is actually `sq`.

> why you added these other languages then?

Do you mean added to the `project-tap.i18n`?

**Comment by frozeman** [comment]
yes

**Comment by luclu** [comment]
Why not?

**Comment by frozeman** [comment]
Do we have translated language files for those?

**Comment by luclu** [comment]
Yes, for Mist - although Albanian is not complete..

But not for the Wallet.

**Comment by frozeman** [comment]
can you rebasE?

**Comment by alexvandesande** [comment]
Superseded by https://github.com/ethereum/mist/pull/910

**Pull request closed without merging**
