### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by Codnova**
Fixed some minor grammar mistakes. I'm not sure if there is other files with Spanish text in it, can somebody tell me where they are so I can take a look?

### CODE REVIEW

**Comment by luclu** [comment]
Hi @Codnova, cool! I also found [mist.es.i18n.json](https://github.com/ethereum/mist/blob/8d9896ffbb440cf6ad4b57a5a5f65768e28d02a0/interface/i18n/mist.es.i18n.json) and [tap-i18n.json
](https://github.com/ethereum/mist/blob/8d9896ffbb440cf6ad4b57a5a5f65768e28d02a0/interface/public/i18n/tap-i18n.json) with Spanish text.

**Comment by luclu** [comment]
@alexvandesande could you enlighten me regarding the wallet-dapp [link](https://github.com/ethereum/meteor-dapp-wallet/tree/master/app/i18n)?

**Comment by alexvandesande** [comment]
Hi @Codnova, don't edit directly the es.json file as this is a generated file. These are the correct source files:

https://github.com/ethereum/mist/blob/develop/interface/i18n/app.en.i18n.json
https://github.com/ethereum/mist/blob/develop/interface/i18n/mist.en.i18n.json
https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/i18n/app.en.i18n.json
https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/i18n/wallet.en.i18n.json

Thanks!

**Comment by franckuestein** [comment]
Exactly @luclu, [app.es.i18n.json](https://github.com/ethereum/mist/blob/master/interface/i18n/app.es.i18n.json) and [mist.es.i18n.json](https://github.com/ethereum/mist/blob/master/interface/i18n/mist.es.i18n.json) are already translated.

I can't see @Codnova changes to review it because it's everything minified in one line on the es.json file.
Can you please create a PR with the changes that you mention updating the [app.es.i18n.json](https://github.com/ethereum/mist/blob/master/interface/i18n/app.es.i18n.json) and [mist.es.i18n.json](https://github.com/ethereum/mist/blob/master/interface/i18n/mist.es.i18n.json) translations?

Thanks!

<hr>

@alexvandesande I'm currently working on the meteor-dapp-wallet spanish translations too. They'll be available soon! 😉

**Comment by alexvandesande** [comment]
@franckuestein is correct. `es.json` is a generated file, created from `app.es.i18n.json` and  `mist.es.i18n.json`

**Pull request closed without merging**
