### PR TITLE
Add change log file.

### PR DESCRIPTION
**Pull request by skywinder**
Hi, as I can see, you are carefully fill tags and labels for issues in your repo.

For such cases I create a [github_changelog_generator](https://github.com/skywinder/github-changelog-generator), that generate change log file based on **tags**, **issues** and merged **pull requests** from :octocat: Issue Tracker.

This PR add change log file to your repo (generated by this script).
You can check, how it is look like here: [Change Log](https://github.com/skywinder/mist/blob/add-change-log-file/CHANGELOG.md)

Some essential features, that has this script:

-  it **exclude** not-related to changelog issues (any issue, that has label `question` `duplicate` `invalid` `wontfix` )
- Distinguish issues **according labels**:
    - Merged pull requests (all `merged` pull-requests)
    - Bug fixes (by label `bug` in issue)
    - Enhancements (by label `enhancement` in issue)
    -   Issues (closed issues `w/o any labels`)
- Generate neat Change Log file according basic [change log guidelines](http://keepachangelog.com).

You can easily update this file in future by simply run script: `github_changelog_generator ethereum/mist` in your repo folder and it make your Change Log file up-to-date again!

Hope you find this commit as useful. :wink:

### CODE REVIEW

**Comment by evertonfraga** [comment]
Hi Petr, thank you for this PR.

After that minor change, It's good to go. Good job! :)

**Comment by bitpshr** [comment]
I noticed this issue stalled out a bit, happy to pick it up.

I'm not sure a change log generated purely on issues will result in a log that's very usable or informative, since many closed issues don't actually result in code changes, and this puts great importance on labeling every issue correctly.

How are the GH releases currently generated? [release](https://github.com/zeit/release) is a very handy tool that's used by many major OSS projects. With a single command, it bumps the package's version using semver (major, minor, or patch), interactively walks through each commit since the last release and asks the user to define if it's a major, minor, or patch change, and then creates a git tag and generates a GH release draft. See an example generated change log [here](https://github.com/zeit/release/releases/tag/3.0.0), and note that before publishing the release, we can add to or edit the generated content.

Assuming `release` could be adopted to generated GH releases to take care of listing every change automatically each with a commit reference, would a `CHANGELOG.md` really be needed?

**Comment by evertonfraga** [comment]
Hi @bitpshr, thanks for picking it up!

The mentioned tool can be configured to only include pull requests, so we'd have a manageable amount of changes. 

However, I love the idea of `release`, a javascript-only approach to this issue. We would be happy to have your contribution ;)

I'm closing this PR.

**Comment by bitpshr** [comment]
Sounds good @evertonfraga. Created #3743 to track progress.

**Pull request closed without merging**
