### PR TITLE
Downloading node client binaries at runtime

### PR DESCRIPTION
**Pull request by hiddentao**
Instead of bundling client binaries at build time we will download then on startup at runtime. This will allow us to update client binaries for all Mist users without having to publish a new Mist release, and it will also reduce the size of Mist/wallet releases. And we will no longer track binaries in the repo (which we should never have done in the first place!). This makes use of [ethereum-client-binaries](https://github.com/hiddentao/ethereum-client-binaries) to facilitate this.

1. It first checks for `ethereumBinaries.json` online in the master repo of Mist project
2. If not found or invalid it will load the one bundled with Mist
3. It will then call into `ethereum-client-binaries` lib with the JSON config and scan for binaries (only Geth supported at the mo)
4. If not matching version of a binary found it will download one and verify again
5. It will then start the app as normal

### CODE REVIEW

**Comment by hiddentao** [comment]
Ready for review. Eth is still bundled as normal whilst I work out how best to fetch it on the fly. Gulp script simplified.

**Comment by luclu** [comment]
Works flawlessly - tested on mac and linux :)

Could you also [cleanup your shrinkwrap](https://github.com/ethereum/mist/pull/1194) by running `npm install; npm prune; npm shrinkwrap`?
Without the prune there will be dev-deps included that won't be available under linux (https://github.com/ethereum/mist/issues/1208).
This will also fix the travis build.

**Comment by hiddentao** [comment]
Thanks @luclu , shrinkwrap updated. Also removed some redundant deps.

**Comment by luclu** [comment]
hmm, seems it didn't work as expected, could you repeat it while `rm -r node_modules` before?

**Comment by hiddentao** [comment]
Tried again, after removing `node_modules`

**Comment by luclu** [comment]
Weird, I pushed my `npm install; npm prune; npm shrinkwrap`'s result then..

**Comment by luclu** [comment]
Ok, made travis happy again while on it.

**Comment by hiddentao** [comment]
Thanks @luclu 

With the frequent new releases of Geth that have been happening recently, this PR would really help in rolling out Geth updates for Mist users.

**Comment by hiddentao** [comment]
Annoyingly am getting build errors again. I've done a fresh `npm shrinkwrap` but to no avail. @luclu I think I need your help again.

**Comment by frozeman** [comment]
One problem with your config is that it downloads all files from peters cross builds. We should download the ones on the github release page from there and only take from peter what we don't get there.

@hiddentao if the config file contains the links to the versions to download, how does the client updates the geth nodes automatically, or checks for new versions? Also howe do we restrict updates to only patch versions, as minor amen major versions could contain backwards incompatible changes.

**Comment by hiddentao** [comment]
@frozeman The download links are arbitrary and can be set to whatever. As long as they link to Zips and Tarballs (i.e. no installers) it's fine.

**Comment by hiddentao** [comment]
Parity binaries available here: https://vanity-service.ethcore.io/parity-binaries

**Comment by luclu** [comment]
@hiddentao no problem, I'm at your disposal ;)
> Annoyingly am getting build errors again. I've done a fresh `npm shrinkwrap` but to no avail. @luclu I think I need your help again.

**Comment by hiddentao** [comment]
Thanks @luclu !

**Comment by evertonfraga** [comment]
Testing checklist:

- [ ]  Start mist without geth nodes on folder
	- [ ] With newer geth on remote json
- [ ] Start mist with geth nodes on folder
	- [ ] Newer geth on remote json
- [ ] Start mist with JSON failing to load
- [ ] Test with Sanity check failing on purpose

**Comment by evertonfraga** [comment]
@hiddentao I've raised https://github.com/hiddentao/ethereum-client-binaries/pull/2 in order to make node updates more reliable.

I'll keep testing.

**Comment by hiddentao** [comment]
@evertonfraga Nice one. Only a minor change needed to that PR and it can be merged.

**Comment by evertonfraga** [comment]
Looks really good to me :)
@hiddentao after integrating that PR, we're good to go

**Comment by hiddentao** [comment]
Fixed CI, ready to merge.

**Pull request merged**
