### PR TITLE
Adjust formatter for addPeer

### PR DESCRIPTION
**Pull request by genecyber**
enode://... doesn't convert to decimal very easily 😀

### CODE REVIEW

**Comment by luclu** [comment]
@genecyber could you please push a dummy commit to get travis (our continuous integration service) running? 
There seems to be some travis-internal problem and this PR did never get into the build queue.
We will be able to merge it as soon as the required check did finish.

Thanks!

**Comment by frozeman** [comment]
It never seems to build

**Comment by genecyber** [comment]
Should I still try and do a other commit to this PR? Or is this a bigger problem?

**Comment by luclu** [comment]
@genecyber yes please, we never encounter this issue with travis, so our hope is that it will build if you push another commit adding or removing just a empty line in some file for example.

If this does not help I will contact travis support to solve this issue on their side.

**Comment by luclu** [comment]
I asked travis to retrigger the stalled build.

**Comment by luclu** [comment]
Travis support is unable to restart, so I recreated the commit: https://github.com/ethereum/mist/pull/1599

**Pull request closed without merging**
