### PR TITLE
Update Geth version, Update Gitter URL

### PR DESCRIPTION
**Pull request by peteski22**
Try to get Mist to use the latest Geth (1.6.7)
(https://github.com/ethereum/mist/issues/2819)

### CODE REVIEW

**Comment by peteski22** [comment]
https://github.com/ethereum/mist/issues/2832

**Comment by PatchRanger** [comment]
@evertonfraga Is it ready for merge? Who is responsible to make that happen? I am experiencing Geth-related issue #2913 - so I am interested in the latest Geth. Could you please force merging of this PR?

**Comment by peteski22** [comment]
Sorry about that, my bad :(

**Comment by evertonfraga** [comment]
No problem :)

**Comment by evertonfraga** [comment]
Solved in separate PRs. 

Thanks @peteski22!

**Pull request closed without merging**
