### PR TITLE
Upgrading electron

### PR DESCRIPTION
**Pull request by evertonfraga**
#### What does it do?

Upgrades to latest stable electron.

### CODE REVIEW

**Comment by nicksavers** [comment]
@evertonfraga Why 1.8.1 and not 1.8.2?
https://github.com/electron/electron/tree/v1.8.2-beta.2

**Comment by evertonfraga** [comment]
@nicksavers at first I thought 1.8.1 wasn't beta, looking at the Tags page (https://github.com/electron/electron/tags).

When I realized it was, I've halted it until they have a stable 1.8 available. Thanks for the sharp eyes :)

**Comment by evertonfraga** [comment]
Put on hold, until we have a stable 1.8.x electron version

**Comment by evertonfraga** [comment]
Upgrading to 1.7.11 instead.

**Pull request merged**
