### PR TITLE
Put human readable function signatures in the transaction confirmation screen.

### PR DESCRIPTION
**Pull request by pipermerriam**
https://github.com/ethereum/mist/issues/955

### What was wrong

When sending a transaction, the user will be better informed if they are able to see more data about the transaction.

### How was this improved

Now the function signature is queried against the [`4byte.directory`](https://www.4byte.directory/) api to try and lookup the human readable signature.

#### Cute animal picture

baby-monkeys-in-clothes-wallpaper-3

### CODE REVIEW

**Comment by pipermerriam** [comment]
screen shot 2016-07-12 at 2 48 13 pm

**Comment by pipermerriam** [comment]
I would ❤️ feedback on this.  I'm utterly new to this codebase and would like to do things "the right way".  Also won't be offended if someone more familiar wants to take this across the finish line at whatever point they feel that is appropriate.

**Comment by frozeman** [comment]
Im at a conference the next two days, but would surely take a look at the code.. Can you please wait until friday?

**Comment by frozeman** [comment]
Code looks good from the first sight, would need to test it though.
We also need to fix the text size in the image, as it is overlapping

**Comment by frozeman** [comment]
Ideally it would also show not only the function, but the actual values inside the function.

Maybe its better to put this then above the bytes data field e.g.

`transferFrom('0x23456789...', 2000)`

**Comment by hiddentao** [comment]
Missing a label.

**Comment by luclu** [comment]
Ah, my mouse acted weird - having its own will lately.. sorry

**Comment by evertonfraga** [comment]
I am moving forward with this PR, and @pipermerriam  I have a question: Is there a way to get updated versions of the whole dictionary, just like [your Gist](https://gist.github.com/pipermerriam/79429c2163969ff732d5f2aabaaaf0e5)? 

I'm thinking of downloading it on every Mist build.

**Comment by pipermerriam** [comment]
The easiest thing might be for me to provide you with a script that scrapes
the data from the API into your desired format.

**Comment by pipermerriam** [comment]
@evertonfraga Here is a python script that demonstrates scraping the API for all signatures.  I imagine it should be easy to transform into something `node` based.

```
import requests
import json

URL = "https://www.4byte.directory/api/v1/signatures/"


def get_all_signatures():
    page = 1
    while True:
        response = requests.get(URL, {'page': page}, headers={'Content-Type': 'application/json'})
        try:
            response.raise_for_status()
        except requests.exceptions.HTTPError:
            break
        response_data = response.json()
        if response_data['count'] == 0:
            break
        for result in response_data['results']:
            yield result
        page += 1


def write_all_signatures():
    with open('signatures.json', 'w') as f:
        signatures = list(get_all_signatures())
        json.dump(signatures, f)


if __name__ == '__main__':
    write_all_signatures()
```

**Comment by alexvandesande** [comment]
replaced by https://github.com/ethereum/mist/pull/1141

**Pull request closed without merging**
