### PR TITLE
Make capitalization more consistent in menus.   Correct punctuation.

### PR DESCRIPTION
**Pull request by greggdourgarian**
Minor text changes

### CODE REVIEW

**Comment by luclu** [comment]
Thank you for this PR, @greggdourgarian!
The stylistic adjdustments look great, but I noticed that you added two spaces between adjusted sentences. Is there a reason for this?
Furthermore the english menu entries on macOS are normally capitalized. Do you use a differnt OS and is this breaking with the norm?

**Comment by greggdourgarian** [comment]
Hi Luca

Thanks for catching the two spaces issue.   That's the style I was educated to use, but it's better to stay consistent with the one space.


Regarding the capitalization of menu items, the concern is that the entries be consistent.  Please note that on the Apple Mac, many profile/os apps aren't consistent - prepositions and conjunctions are capitalized sometimes, and sometimes they are not.


On Mist, it appeared to me that most entries followed the rule of capitalizing only the first letter of an item and of proper nouns.   My changes should just reflect that rule so as to make them all consistent.




________________________________
________________________________

**Comment by evertonfraga** [comment]
After merge, i'll fix the double spacing.

**Comment by greggdourgarian** [comment]
?great!  i can do it if you want though


Gregg
cell: 1-651-324-7376
________________________________
________________________________

**Comment by greggdourgarian** [comment]
hey Luca...i have some time coming up to work on the code in Mist shell and wallet code.  Do you have an unworked issue list going?



Gregg
cell: 1-651-324-7376
________________________________
________________________________

**Pull request merged**
