### PR TITLE
Version of geth which fixes #182

### LINKED ISSUE #182: Not able to import used presale wallet
I am used to import part of my presale ethers using Kraken's presale importing tool. There is 0.07 Ether left in my presale file. Trying to import this wallet into Mist gives me "wrong password" error.

### PR DESCRIPTION
**Pull request by hiddentao**
This version of geth incorporates ethereum/go-ethereum#2371 to fix #182 and other related issues.

### CODE REVIEW

**Comment by frozeman** [comment]
So you've build all three? @alexvandesande @fjl should we use this version for now to quick fix the presale import?

**Comment by fjl** [comment]
We will release geth 1.3.6 soon and it will include this fix.

**Comment by hiddentao** [comment]
Shall we close this one? It's against `master` anyway.

**Comment by fjl** [comment]
geth 1.3.6 is released.

**Pull request closed without merging**
