### PR TITLE
Sidebar revamp

### PR DESCRIPTION
**Pull request by evertonfraga**
This is a work in progress.

- [x] Mask icons with superellipse SVG
- [x] Use of large icons on each tab
- [x] Add tip on selected tab, to improve visibility
- [x] Add tabs scroll area
- [x] Tab floating submenu
- [x] Deal with submenu cursor path [see full story](http://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown)
- [x] submenu padding
- [x] z-index issue with Navbar
- [x] Review drag-and-drop
- [x] Scrollbar on Linux/win
- [x] Blinking scrollbar glitch on osx

Current state: 
image

### CODE REVIEW

**Comment by evertonfraga** [comment]
Still need some improvements, but here's how tabs scrolling work:

scrollable-tabs mov

**Comment by frozeman** [comment]
It would be great to see the app name when hovering over them, otherwise its not clear which ones are those, for the ones without icon

**Comment by evertonfraga** [comment]
Current state: 

image

image

image

**Comment by frozeman** [comment]
beautiful.
Did you thought about how it looks on windows with the scrollbar? We might need to increase the width there.

**Comment by evertonfraga** [comment]
Almost ready, guys. I have to fix windows and linux small issues, and a small bug on the menu position I just discovered.

**Comment by luclu** [comment]
Wow this looks and feels awesome!

Some issue I stumbled into after defocusing the window:
(BTW I started using https://getkap.co for screencapturing gifs :))

kapture 2017-03-23 at 0 02 02

**Comment by evertonfraga** [comment]
Yes! their position was ok until I fixed the drag and drop.

**Pull request merged**
