### PR TITLE
Add French i18n

### PR DESCRIPTION
**Pull request by V1C0D3R**

### CODE REVIEW

**Comment by frozeman** [comment]
Merci!

**Comment by frozeman** [comment]
Could you also translate the wallet itself? https://github.com/ethereum/meteor-dapp-wallet/tree/develop/app/i18n

**Comment by V1C0D3R** [comment]
Yes, I began but Wallet's i18n is not ready yet (part of it is in english tho). Do you want me to open a pull request ? https://github.com/V1C0D3R/meteor-dapp-wallet/commit/873f86e14466ee6d7d3c371824d51a6e6a428dc3

**Comment by frozeman** [comment]
Its fine, i can wait until its finished
>

**Pull request merged**
