### PR TITLE
Adding contrast on dark themes

### LINKED ISSUE #702: unreadable text on gnome dark theme
As reported in this issue: https://github.com/ethereum/mist/issues/523

### PR DESCRIPTION
**Pull request by evertonfraga**
fixes #702

### CODE REVIEW

**Comment by alexvandesande** [comment]
Do you have any screenshots on linux?

**Comment by luclu** [comment]
bildschirmfoto 2016-07-25 um 19 57 17

**Comment by alexvandesande** [comment]
Mmmm. Doesn't help so much with the contrast does it?

**Comment by luclu** [comment]
Well, it is possible to read it now on dark themes - currently it is like this:

**Comment by evertonfraga** [comment]
@alexvandesande @luclu any more considerations? shall we merge?

**Pull request merged**
