### PR TITLE
change mining hotkey to free minizing hotkey

### LINKED ISSUE #552: OSX: Minimize by pressing ⌘M
Currently Mining `CommandOrControl+M` is blocking this OS standard.
I propose `CommandOrControl+Shift+M` for mining instead.

### PR DESCRIPTION
**Pull request by luclu**
From `CMD/CTRL + M` (Minimizing)
to `CMD/CTRL + SHIFT + M`.
fixes #552

### CODE REVIEW

**Comment by alexvandesande** [comment]
@luclu since we are changing keyboard shortcuts, could you also fix this issue on this same PR?

https://github.com/ethereum/mist/issues/379

**Comment by luclu** [comment]
those seem the easiest/logical substitute, should be free from collisions and go in the same rationale as the mining-hotkey-change.

**Comment by luclu** [comment]
@alexvandesande @frozeman @hiddentao 
How is the new key's flavor for you?

**Comment by alexvandesande** [comment]
awesome, thanks

**Pull request merged**
