### PR TITLE
Store network id with Mongo data

### PR DESCRIPTION
**Pull request by hiddentao**
At the moment all account data and such are stored without any reference to the network they're related to, causing umpteen problems when switching network. This PR fixes that by ensuring a network indicator (Genesis block hash) gets stored with the data.
- ethereum/meteor-dapp-wallet#276
- ethereum/mist#1049
- ethereum/meteor-package-accounts#2
- ethereum/meteor-package-blocks#1

### CODE REVIEW

**Comment by hiddentao** [comment]
Refactored network info fetching code into [hiddentao/meteor-ethereum-networkinfo](/hiddentao/meteor-ethereum-networkinfo)

**Comment by hiddentao** [comment]
@frozeman @luclu @evertonfraga @alexvandesande ready for review

**Comment by hiddentao** [comment]
Updated networkinfo pkg version.

**Comment by tjayrush** [comment]
@hiddentao I'm not certain, but my guess is that this pull request will fix this issue as well:  https://github.com/ethereum/mist/issues/541

**Pull request closed without merging**
